version: b{build}

branches:
  except:
    - gh-pages

install:
  - cinst php

build_script:
  - make.bat

test_script:
  - PATH=C:\tools\php;%PATH%
  - "cd node && npm install"
  - make integration

artifacts:
  - path: watchman.exe
    name: watchman
    type: zip
